#! /usr/bin/env zsh

if [[ -z "$1" ]]; then
    echo "cljsProject: missing project name"
    exit 1
fi

mkdir -p ${1}/src/${1}
cp ~/.zsh/scripts/CLJS_TEMPLATES/main.cljs ${1}/src/${1}
sed -i "s/\${PROJECT_NAME}/${1}/g" ${1}/src/${1}/main.cljs

mkdir -p ${1}/test/${1}
cp ~/.zsh/scripts/CLJS_TEMPLATES/main_test.cljs ${1}/test/${1}
sed -i "s/\${PROJECT_NAME}/${1}/g" ${1}/test/${1}/main_test.cljs

cp ~/.zsh/scripts/CLJS_TEMPLATES/deps.edn  ${1}
cp ~/.zsh/scripts/CLJS_TEMPLATES/tools.clj ${1}
sed -i "s/\${PROJECT_NAME}/${1}/g" ${1}/tools.clj

