#!/usr/bin/env zsh

if [[ -z "$1" ]]; then
    echo "cljsProject: missing project name"
    exit 1
fi

mkdir -p ${1}/src/${1}
mkdir -p ${1}/test/${1}

cp ~/.zsh/scripts/CLJS_TEMPLATES/main.cljs ${1}/src/${1}
cp ~/.zsh/scripts/CLJS_TEMPLATES/main_test.cljs ${1}/test/${1}
cp ~/.zsh/scripts/CLJS_TEMPLATES/deps.edn ${1}
cp ~/.zsh/scripts/CLJS_TEMPLATES/makefile.clj ${1}

find $1 -type f | xargs -I{} sed -i "s/\${PROJECT_NAME}/${1}/g" {}

