#! /usr/bin/env zsh

if [[ -z "$1" ]]; then
    echo 'cljsProject: missing project name'
    exit 1
fi

mkdir -p ${1}/src/${1}

echo "(ns ${1}.core
  (:require [cljs.nodejs :as nodejs]))

(nodejs/enable-util-print!)

(defn -main
  [& args]
  (println \"Hello world!\"))

(set! *main-cli-fn* -main)" > ${1}/src/${1}/core.cljs

echo "(defproject ${1} \"0.1.0-SNAPSHOT\"
  :source-paths [\"src\"]
  :dependencies [[org.clojure/clojure \"1.10.1\"]
                 [org.clojure/clojurescript \"1.10.520\"]]
  :plugins [[lein-cljsbuild \"1.1.8\"]]
  :cljsbuild {:builds [{:source-paths [\"src\"]
                        :compiler {:main ${1}.core
                                   :output-to \"main.js\"
                                   :output-dir \"out\"
                                   :target :nodejs
                                   :verbose true}}]})" > ${1}/project.clj

